language: node_js
node_js:
  - '6'
sudo: false
script:
  - "npm run test-cov"
after_script: "npm install coveralls && cd test-cov &&  cat coverage.lcov | ../node_modules/coveralls/bin/coveralls.js && cd .. && rm -rf ./test-cov && rm -rf ./test-app"